### ISSUE TITLE
1.0 release roadmap

### ISSUE THREAD

**Issue by sjwilczynski** [sjwilczynski/WNOPBudgetAutocomplete#1]
Required:

* [x] add proper readme
* [x] rename to make sure no weird strings show up
* [x] fix CSS
* [x] add (continous) deployment
* [x] localize error messages to polish
* [x] compare with original excel sheet and review potentail discrepancies (e.g "." in Wzorze kategorii), number of whitespaces, etc.
* [x] ~~find a better way to get categories names than hardcoding locations (e.g. listing tables)~~ (after thinking it through there doesn't seem to be a better way - the [app built by other community members](https://github.com/pawegio/HomeBudget) also hardcodes location of categories
* [x] add new icons

Optional:

* [x] add proper localization (polish/english)
* [x] fix linter complaints
* [x] do dependencies cleanup
* [x] do manifest cleanup
* [x] replace hot loader with Fast Refresh
